import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useQuery,gql } from "@apollo/client";
import client from "../components/apollo_client";



export default function Home() {
  const { data,loading,error } = useQuery(gql`
      query ExampleQuery {
        users {
          name
          rocket
          twitter
        }
      }
    `,
  );
  if(loading){
  <p>...loading</p>
  }
  if(error){
    <p>Ops. Error</p>
    }
  console.log("data",data?.users);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.grid}>
          {data?.users.map((user) => (
            <div className={styles.card} key={user.name}>
              <h2>{user.name}</h2>
              </div>))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
